name: ci

on:
  push:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: docker compose up -d

      - name: install
        run: docker compose -f docker-compose.test-runner.yml run --rm --entrypoint qlot batis-test install

      - name: Test
        run: docker compose -f docker-compose.test-runner.yml run --rm --entrypoint qlot batis-test exec rove batis-test.asd
